#!/bin/sh

version=6.1.74

if [ $(command -v dracut) ]; then
	echo "dracut: generating initramfs for kernel $kver..."
	dracut --force --kver ${version}-v8-16k /boot/initramfs.img
fi

depmod ${version}-v8-16k
